global:
  # disablePolicyChecks disables mixer policy checks.
  # if mixer.policy.enabled==true then disablePolicyChecks takes effect.
  disablePolicyChecks: false
  mtls:
    enabled: false
  proxy:
    accessLogFile: "/dev/stdout"
    init:
      resources:
        requests:
          cpu: 10m
    resources:
      requests:
        cpu: 10m
        
gateways:
  enabled: true
  istio-ingressgateway:
    autoscaleEnabled: false
    type: ClusterIP
    ports:
    ## You can add custom gateway ports
    # Note that AWS ELB will by default perform health checks on the first port
    # on this list. Setting this to the health check port will ensure that health
    # checks always work. https://github.com/istio/istio/issues/12503
    - port: 15020
      targetPort: 15020
      name: status-port
    - port: 80
      targetPort: 80
      name: http2
    - port: 443
      name: https
    # Example of a port to add. Remove if not needed
    - port: 31400
      name: tcp
      nodePort: 31400
    ### PORTS FOR UI/metrics #####
    ## Disable if not needed
    - port: 15029
      targetPort: 15029
      name: https-kiali
    - port: 15032
      targetPort: 15032
      name: https-tracing
  istio-egressgateway:
    autoscaleEnabled: false
  istio-ilbgateway:
    autoscaleEnabled: false
    
grafana:
  enabled: false
  
kiali:
  enabled: true

mixer:
  enabled: true
  telemetry:
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
  policy:
    autoscaleEnabled: false

pilot:
  # traceSample default 10%
  traceSampling: 100
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 10m
      memory: 100Mi

prometheus:
  enabled: true
            
tracing:
  enabled: true
  ingress:
    enabled: true
